export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEES_SUCESSED = "GET_EMPLOYEES_SUCESSED";
export const GET_EMPLOYEES_FAILED = "GET_EMPLOYEES_FAILED";

export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADD_EMPLOYEE_SUCCESSED = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILED = "ADD_EMPLOYEE_FAILED";

export const ID = "ID";

export const GET_EMPLOYEE_DETAIL = "GET_EMPLOYEE_DETAIL";
export const GET_EMPLOYEE_DETAIL_SUCESSED = "GET_EMPLOYEE_DETAIL_SUCESSED";
export const GET_EMPLOYEE_DETAIL_FAILED = "GET_EMPLOYEE_DETAIL_FAILED";

export const DELETE_EMPLOYEE_SHOW_MODAL = "DELETE_EMPLOYEE_SHOW_MODAL";
export const DELETE_EMPLOYEE_HIDE_MODAL = "DELETE_EMPLOYEE_HIDE_MODAL";

export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_SUCESSED = "DELETE_EMPLOYEE_SUCESSED";
export const DELETE_EMPLOYEE_FAILED = "DELETE_EMPLOYEE_FAILED";


export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_SUCESSED = "UPDATE_EMPLOYEE_SUCESSED"
export const UPDATE_EMPLOYEE_FAILED = "UPDATE_EMPLOYEE_FAILED";
